version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - make build
      - aws cloudformation package --template-file ./stacks/accounts-janitor-account/inspector.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix artifacts/horatio/inspector --output-template-file ./stacks/accounts-janitor-account/inspector.yml
artifacts:
  files: "**/*"
