Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for horatio inspector
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Resources:
  FunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: !Sub "${Environment}-horatio-inspector-execution-role"
      Policies:
        - PolicyName: horatio-inspector-execution-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - arn:aws:iam::008356366354:role/horatio-list-accounts-role
                  - arn:aws:iam::*:role/horatio-inspection-target-account-role
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - Fn::ImportValue: !Sub "${Environment}-horatio-report-queue-arn"
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: inspector.main.handler
      Runtime: python3.9
      CodeUri: ../../../apps/inspector/build
      Role: !GetAtt FunctionExecutionRole.Arn
      FunctionName: !Sub "${Environment}-horatio-inspector"
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          QUEUE_URL:
            Fn::ImportValue: !Sub "${Environment}-horatio-report-queue-url"
          POWERTOOLS_SERVICE_NAME: horatio-inspector
          LOG_LEVEL: INFO
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: !Sub "${Environment}-horatio-inspector-scheduler-role"
      Policies:
        - PolicyName: horatio-inspector-scheduler-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt Function.Arn
  VPCSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${Environment}-horatio-inspector-vpc"
      ScheduleExpression: cron(30 08 * * ? *)
      ScheduleExpressionTimezone: Europe/London
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt Function.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: |
          {
            "SERVICE": "VPC",
            "REGIONS": ["eu-west-1", "eu-west-2", "us-east-1"]
          }
  EC2Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${Environment}-horatio-inspector-ec2"
      ScheduleExpression: cron(30 08 * * ? *)
      ScheduleExpressionTimezone: Europe/London
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt Function.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: |
          {
            "SERVICE": "EC2",
            "REGIONS": ["eu-west-1", "eu-west-2", "us-east-1"]
          }
  BudgetsSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${Environment}-horatio-inspector-budgets"
      ScheduleExpression: cron(30 08 * * ? *)
      ScheduleExpressionTimezone: Europe/London
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt Function.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: |
          {
            "SERVICE": "BUDGETS",
            "REGIONS": ["eu-west-1"]
          }
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Namespace: AWS/Lambda
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Statistic: Sum
      Threshold: 0
      ActionsEnabled: true
      AlarmActions:
        - !ImportValue notification-topic
      Dimensions:
        - Name: FunctionName
          Value: !Ref Function
