Description: pipeline to deploy horatio
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !ImportValue ci-infrastructure-codebuild-base-policy
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !ImportValue ci-infrastructure-build-artifacts-bucket-name
        Path: /artifacts/horatio/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds horation
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Value: !ImportValue ci-infrastructure-build-artifacts-bucket-name
            Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
      Name: horatio
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !ImportValue ci-infrastructure-build-artifacts-bucket-name
      Name: horatio
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue ci-infrastructure-codepipeline-base-execution-role
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Namespace: SourceVariables
              Configuration:
                ConnectionArn: !ImportValue ci-infrastructure-codestar-connection
                FullRepositoryId: AlexChesters/horatio
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
        - Name: Build-Lambdas
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              OutputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy-Common-Resources-To-Test
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: DynamoDB
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-horatio-common-resources-dynamo
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/common-resources/dynamo.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/common-resources/parameters/dynamo/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: SQS
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-horatio-common-resources-sqs
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/common-resources/sqs.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/common-resources/parameters/sqs/test.json
        - Name: Deploy-Lambdas-To-Test
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Inspector
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-horatio-inspector
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/apps/inspector.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/apps/parameters/inspector/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Recorder
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-horatio-recorder
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/apps/recorder.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/apps/parameters/recorder/test.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Reporter
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: test-horatio-reporter
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/apps/reporter.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/apps/parameters/reporter/test.json
        - Name: Deploy-Common-Resources-To-Live
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: DynamoDB
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-horatio-common-resources-dynamo
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/common-resources/dynamo.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/common-resources/parameters/dynamo/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: SQS
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-horatio-common-resources-sqs
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/common-resources/sqs.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/common-resources/parameters/sqs/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: SES
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-horatio-common-resources-ses
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/common-resources/ses.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/common-resources/parameters/ses/live.json
        - Name: Deploy-Lambdas-To-Live
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Inspector
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-horatio-inspector
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/apps/inspector.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/apps/parameters/inspector/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Recorder
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-horatio-recorder
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/apps/recorder.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/apps/parameters/recorder/live.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Reporter
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: live-horatio-reporter
                RoleArn: !ImportValue ci-infrastructure-codepipeline-base-cloudformation-role
                TemplatePath: BuiltSource::stacks/accounts-janitor-account/apps/reporter.yml
                TemplateConfiguration: BuiltSource::stacks/accounts-janitor-account/apps/parameters/reporter/live.json
