Description: SQS infrastructure for Horatio
Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - test
      - live
Resources:
  DLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: !Sub "${Environment}-horatio-recorder-dlq"
      MessageRetentionPeriod: 604800
  ReportQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: !Sub "${Environment}-horatio-report-queue"
      MessageRetentionPeriod: 259200
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DLQ.Arn
        maxReceiveCount: 3
Outputs:
  QueueUrl:
    Export:
      Name: !Sub "${Environment}-horatio-report-queue-url"
    Value: !Ref ReportQueue
  QueueName:
    Export:
      Name: !Sub "${Environment}-horatio-report-queue-name"
    Value: !GetAtt ReportQueue.QueueName
  QueueArn:
    Export:
      Name: !Sub "${Environment}-horatio-report-queue-arn"
    Value: !GetAtt ReportQueue.Arn
