Description: IAM role for use by AlexChesters/horatio to allow account listing
Resources:
  LogGroupEnforcerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::723247229166:role/test-horatio-inspector-execution-role
                - arn:aws:iam::723247229166:role/live-horatio-inspector-execution-role
              Service:
                - lambda.amazonaws.com
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::723247229166:root
            Condition:
              StringEquals:
                aws:PrincipalOrgID: o-hru7a3vwm2
              ArnLike:
                aws:PrincipalARN: arn:aws:iam::723247229166:role/aws-reserved/sso.amazonaws.com/*
      RoleName: horatio-list-accounts-role
      Policies:
        - PolicyName: horatio-list-accounts-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - organizations:ListAccounts
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - cloudformation:ListStackInstances
                Resource:
                  - !Sub "arn:${AWS::Partition}:cloudformation:eu-west-1:${AWS::AccountId}:stackset/horatio-inspection-role:*"
